Update PPP - Cheng Hin
AY2021S1-CS2103T-F13-4/tp pull request #188
Opened 2020-11-05 15:30 UTC by bchenghi

2020-11-05 16:33 UTC, SONGYI98 requested changes
Just a minor edit required.

2020-11-05 16:33 UTC, SONGYI98 commented on docs/team/bchenghi.md
> +    * Justification: Previously, a `Person` was a duplicate if it had the same `Name`, and either the same `Email` or `Phone`. This no longer applied to the application after the first iteration as t
Need to switch to the context of Food.

2020-11-05 17:25 UTC, bchenghi commented on docs/team/bchenghi.md
> +    * Justification: Previously, a `Person` was a duplicate if it had the same `Name`, and either the same `Email` or `Phone`. This no longer applied to the application after the first iteration as t
Thanks! Changed.

2020-11-06 03:02 UTC, SONGYI98 approved these changes
LGTM

2020-11-06 03:02 UTC, merged